### ISSUE TITLE
Possible organization for future projects?

### ISSUE THREAD

**Issue by ev3commander** [TropicSapling/Vector-World#2]
We could have an organization so we can also put future projects in there.
Click plus sign-> new organization. You should name it VectorWorld (or Vector-World or... You get the point.) 

Then we could also have a website VectorWorld.github.io.

**Comment by TropicSapling** [comment]
I had a website previously but since gwiddle.org was shut down I haven't re-created the website yet :(
But I'll probably re-make it in the future :)

**Anyway**, about the organization, what about the name "Vector World Foundation (VWF)" or "Sapling"?

**Comment by ev3commander** [comment]
^^ The rules for an org is the same as an account. Only alphanumeric, -, and _. 

(move this to [here](//gitter.im/ev3commander/vectorworld)?)

**Comment by TropicSapling** [comment]
**An organization, VWF (Vector-World-Foundation), has been added!**
